# Generated by Django 3.0.1 on 2019-12-26 22:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.TextField(blank=True)),
                ('category_type', models.TextField(choices=[('1', '品牌'), ('2', '一级分类'), ('3', '二级分类')], default='1', max_length=1)),
                ('is_root', models.BooleanField(default=False)),
                ('icon', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carousel', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=255)),
                ('weight', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField(default='')),
                ('slug', models.TextField(blank=True)),
                ('header_image', models.URLField()),
                ('video_url', models.URLField(blank=True, default='')),
                ('sold', models.IntegerField(default=0)),
                ('fav', models.IntegerField(default=0)),
                ('pv', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=1)),
                ('review', models.IntegerField(default=0)),
                ('has_invoice', models.BooleanField(default=True)),
                ('ship_free', models.BooleanField(default=True)),
                ('refund', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('status', models.TextField(choices=[('1', '上架'), ('2', '下架'), ('3', '预售')], default='1', max_length=1)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, default='', max_length=255)),
                ('subtitle', models.CharField(db_index=True, default='', max_length=255)),
                ('subsubtitle', models.CharField(db_index=True, default='', max_length=255)),
                ('display_order', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '推荐商品',
                'verbose_name_plural': '推荐商品',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, default='')),
                ('image', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('type', models.TextField(choices=[('1', '好评'), ('2', '中评'), ('3', '差评')], default='1', max_length=1)),
                ('rate', models.IntegerField(default=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='products.Product')),
            ],
            options={
                'verbose_name': '商品评价评分',
                'verbose_name_plural': '商品评价评分',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('header_image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('can_loss', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('sn', models.CharField(default='', max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='products.Product')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReviewAppend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default='')),
                ('product_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review_appends', to='products.ProductReview')),
            ],
            options={
                'verbose_name': '商品评价追加',
                'verbose_name_plural': '商品评价追加',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='productreview',
            name='product_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_spec_reviews', to='products.ProductSpec'),
        ),
    ]
