# Generated by Django 3.0.1 on 2019-12-28 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191226_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.TextField(choices=[('1', '上架'), ('2', '下架')], default='1', max_length=1),
        ),
    ]
