# Generated by Django 3.0.1 on 2020-01-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_root',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_invoice',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='refund',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='ship_free',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='can_loss',
            field=models.NullBooleanField(default=None),
        ),
    ]
