# Generated by Django 3.0.2 on 2020-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200107_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.TextField(choices=[('1', '品牌'), ('2', '一级分类'), ('3', '二级分类')], default='2', max_length=1),
        ),
    ]
