# Generated by Django 3.0.2 on 2020-01-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200119_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='content',
            new_name='desc',
        ),
    ]
