# Generated by Django 3.0.2 on 2020-02-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200125_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.NullBooleanField(default=True),
        ),
    ]
