# Generated by Django 3.0.5 on 2020-05-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200427_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_vip',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vip_expired_datetime',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vip_session',
        ),
    ]
