# Generated by Django 3.0.1 on 2019-12-26 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('express', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='express',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_express', to='transactions.Transaction'),
        ),
    ]
