# Generated by Django 3.0.5 on 2020-05-06 14:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20200506_1453'),
        ('transactions', '0004_auto_20200427_1633'),
        ('express', '0002_express_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='merchant',
            field=models.ForeignKey(help_text='商户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_express', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='express',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='快递信息', null=True),
        ),
        migrations.AlterField(
            model_name='express',
            name='shipper_code',
            field=models.CharField(blank=True, default='', help_text='快递单号', max_length=255),
        ),
        migrations.AlterField(
            model_name='express',
            name='shipper_name',
            field=models.CharField(blank=True, default='', help_text='快递名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='express',
            name='status',
            field=models.TextField(choices=[('0', '商家打包'), ('1', '揽收'), ('2', '在途'), ('3', '签收'), ('4', '其他')], default='0', help_text='快递状态', max_length=1),
        ),
        migrations.AlterField(
            model_name='express',
            name='transaction',
            field=models.OneToOneField(help_text='订单', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_express', to='transactions.Transaction'),
        ),
    ]
