# Generated by Django 3.0.1 on 2019-12-26 22:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, default='')),
                ('mobile', models.CharField(blank=True, default='', max_length=11)),
                ('deleted', models.BooleanField(default=False)),
                ('services_id_and_secret', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': '商户',
                'verbose_name_plural': '商户',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
