# Generated by Django 3.0.2 on 2020-02-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='services_id_and_secret',
            new_name='services_key',
        ),
    ]
