# Generated by Django 3.0.5 on 2020-05-06 14:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_auto_20200206_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='mobile',
            field=models.CharField(blank=True, default='', help_text='手机号', max_length=11),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(help_text='名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='remark',
            field=models.TextField(blank=True, default='', help_text='备注'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='services_key',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='API KEY AND SECRET JSON', null=True),
        ),
    ]
