# Generated by Django 3.0.1 on 2019-12-26 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_productreview_transaction'),
        ('assist', '0002_auto_20191226_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_aritcles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_articles', to='merchant.Merchant'),
        ),
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products_articles', to='products.Product'),
        ),
        migrations.AddField(
            model_name='article',
            name='specs',
            field=models.ManyToManyField(blank=True, related_name='product_specs_articles', to='products.ProductSpec'),
        ),
    ]
