# Generated by Django 3.0.1 on 2019-12-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0003_auto_20191226_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='specs',
        ),
    ]
