# Generated by Django 3.0.1 on 2019-12-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0004_remove_article_specs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
