# Generated by Django 3.0.5 on 2020-05-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20200506_1453'),
        ('products', '0010_auto_20200427_1633'),
        ('assist', '0005_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.URLField(help_text='链接'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='display_order',
            field=models.IntegerField(default=1, help_text='展示顺序'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='merchant',
            field=models.ForeignKey(help_text='商户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_banners', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(help_text='名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(blank=True, help_text='商品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_banners', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.TextField(choices=[('1', '上线'), ('2', '下线')], default='2', help_text='状态', max_length=1),
        ),
        migrations.AlterField(
            model_name='notice',
            name='desc',
            field=models.TextField(blank=True, default='', help_text='描述'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='header_image',
            field=models.URLField(blank=True, default='', help_text='题图'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='link',
            field=models.URLField(blank=True, default='', help_text='链接'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='merchant',
            field=models.ForeignKey(help_text='商户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_notices', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='sent',
            field=models.BooleanField(default=False, help_text='已发送'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='sent_datetime',
            field=models.DateTimeField(blank=True, help_text='发送时间', null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(help_text='标题', max_length=255),
        ),
        migrations.AlterField(
            model_name='splash',
            name='link',
            field=models.CharField(blank=True, default='', help_text='链接', max_length=255),
        ),
        migrations.AlterField(
            model_name='splash',
            name='merchant',
            field=models.ForeignKey(help_text='商户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_splashs', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='splash',
            name='name',
            field=models.CharField(help_text='名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='splash',
            name='product',
            field=models.ForeignKey(blank=True, help_text='商品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_splash', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='splash',
            name='splash',
            field=models.URLField(help_text='链接'),
        ),
        migrations.AlterField(
            model_name='splash',
            name='status',
            field=models.TextField(choices=[('1', '上线'), ('2', '下线')], default='2', help_text='状态', max_length=1),
        ),
    ]
