# Generated by Django 3.0.1 on 2019-12-26 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.TextField(choices=[('1', '会员优惠卷'), ('2', '积分优惠卷'), ('3', '普通优惠卷')], default='3', max_length=1)),
                ('internal_type', models.TextField(choices=[('1', '全场满金额减'), ('2', '分类满金额减'), ('3', '单品满金额减'), ('4', '全场满件数减'), ('5', '分类满件数减'), ('6', '单品满件数减')], default='2', max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
                ('reach_price', models.DecimalField(blank=True, decimal_places=2, help_text='满金额使用', max_digits=8, null=True)),
                ('reach_unit', models.IntegerField(blank=True, help_text='满几件使用，分类满几件，单品满几件', null=True)),
                ('discount_price', models.DecimalField(decimal_places=2, help_text='减价格，必填', max_digits=8)),
                ('start_datetime', models.DateTimeField(help_text='可使用开始时间')),
                ('end_datetime', models.DateTimeField(help_text='可使用结束时间')),
                ('total', models.IntegerField(default=10, help_text='发放数量')),
                ('left', models.IntegerField(default=10, help_text='剩余数量')),
                ('points', models.IntegerField(blank=True, help_text='需要多少积分兑换', null=True)),
                ('outdated', models.BooleanField(default=False, help_text='是否过期，过期后不在前端展示')),
                ('in_use', models.BooleanField(default=True, help_text='是否开放使用')),
            ],
            options={
                'verbose_name': '优惠卷',
                'verbose_name_plural': '优惠卷',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used', models.BooleanField(default=False, help_text='是否使用')),
                ('used_datetime', models.DateTimeField(blank=True, help_text='使用时间', null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_coupon_logs', to='coupons.Coupon')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_coupon_logs', to='merchant.Merchant')),
            ],
            options={
                'verbose_name': '优惠卷记录',
                'verbose_name_plural': '优惠卷记录',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
