# Generated by Django 3.0.1 on 2019-12-26 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('merchant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_productreview_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupon_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(blank=True, help_text='品牌或分类可用', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_coupons', to='products.Category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_coupons', to='merchant.Merchant'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(blank=True, help_text='指定商品可用', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_coupons', to='products.Product'),
        ),
    ]
