# Generated by Django 3.0.1 on 2019-12-26 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        ('merchant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20191226_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_product_promotions', to='merchant.Merchant'),
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='product_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_spec_product_promotions', to='products.ProductSpec'),
        ),
        migrations.AddField(
            model_name='log',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_promotion_logs', to='merchant.Merchant'),
        ),
        migrations.AddField(
            model_name='log',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_logs', to='promotions.Promotion'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_promotion_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
