# Generated by Django 3.0.1 on 2020-01-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20191226_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='current_nums',
        ),
    ]
