# Generated by Django 3.0.1 on 2019-12-26 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('feedback', '0002_feedback_product_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='transaction_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_product_feedbacks', to='transactions.TransactionProduct'),
        ),
    ]
