# Generated by Django 3.0.5 on 2020-05-06 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant', '0003_auto_20200506_1453'),
        ('transactions', '0004_auto_20200427_1633'),
        ('products', '0010_auto_20200427_1633'),
        ('feedback', '0004_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(help_text='内容'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='merchant',
            field=models.ForeignKey(help_text='商户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_feedbacks', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='product_spec',
            field=models.ForeignKey(blank=True, help_text='商品规格', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_spec_feedbacks', to='products.ProductSpec'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='solved',
            field=models.BooleanField(default=False, help_text='是否解决'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='transaction_product',
            field=models.ForeignKey(blank=True, help_text='订单商品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_product_feedbacks', to='transactions.TransactionProduct'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.TextField(choices=[('1', '投诉'), ('2', '售后'), ('3', '求购'), ('4', '咨询')], default='4', help_text='类型', max_length=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, help_text='用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
