# Generated by Django 3.0.2 on 2020-01-08 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_remove_promotion_current_nums'),
        ('transactions', '0002_auto_20191226_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_transactions', to='promotions.Promotion'),
        ),
    ]
