# Generated by Django 3.0.4 on 2020-04-27 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
        ('coupons', '0002_auto_20191226_2252'),
        ('promotions', '0003_remove_promotion_current_nums'),
        ('merchant', '0002_auto_20200206_1241'),
        ('profiles', '0003_auto_20200427_1633'),
        ('products', '0010_auto_20200427_1633'),
        ('transactions', '0003_transaction_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='merchant',
            field=models.ForeignKey(help_text='商户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_collects', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='mobile',
            field=models.CharField(help_text='手机号', max_length=11),
        ),
        migrations.AlterField(
            model_name='collect',
            name='name',
            field=models.CharField(help_text='名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='collect',
            name='note',
            field=models.CharField(blank=True, default='', help_text='备注', max_length=255),
        ),
        migrations.AlterField(
            model_name='collect',
            name='picked',
            field=models.BooleanField(default=False, help_text='自提完成'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='picked_datetime',
            field=models.DateTimeField(blank=True, help_text='自提时间', null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='pickup_datetime',
            field=models.DateTimeField(help_text='自提时间'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='store',
            field=models.ForeignKey(help_text='门店', on_delete=django.db.models.deletion.CASCADE, related_name='store_collects', to='stores.Store'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='transaction',
            field=models.OneToOneField(help_text='订单', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_collect', to='transactions.Transaction'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.ForeignKey(blank=True, help_text='地址', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_invoices', to='profiles.Address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_tax_sn',
            field=models.CharField(blank=True, default='', help_text='税号', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued',
            field=models.BooleanField(default=False, help_text='是否已开票'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_datetime',
            field=models.DateTimeField(blank=True, help_text='开票时间', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='merchant',
            field=models.ForeignKey(help_text='商户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_invoices', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='发票金额', max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipped',
            field=models.BooleanField(default=False, help_text='是否发出快递'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipped_datetime',
            field=models.DateTimeField(blank=True, help_text='快递发出时间', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(help_text='发票抬头', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transaction',
            field=models.OneToOneField(help_text='订单', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_invoice', to='transactions.Transaction'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.TextField(blank=True, choices=[('1', '普通发票'), ('2', '公司发票')], default='1', help_text='发票类型', max_length=1),
        ),
        migrations.AlterField(
            model_name='refund',
            name='audit',
            field=models.TextField(choices=[('1', '审核中'), ('2', '通过'), ('3', '未通过'), ('4', '运输中'), ('5', '退款完成'), ('6', '撤销')], default='1', help_text='退货状态', max_length=1),
        ),
        migrations.AlterField(
            model_name='refund',
            name='audit_datetime',
            field=models.DateTimeField(blank=True, help_text='审核时间', null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='audit_note',
            field=models.TextField(blank=True, default='', help_text='审核备注'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='auditor',
            field=models.ForeignKey(blank=True, help_text='退货审核人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditor_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='merchant',
            field=models.ForeignKey(help_text='商户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_refunds', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='note',
            field=models.TextField(default='', help_text='备注'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_enter_ship_info_datetime',
            field=models.DateTimeField(blank=True, help_text='快递进入揽收时间', null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_price',
            field=models.DecimalField(decimal_places=2, help_text='退货金额', max_digits=8),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.TextField(choices=[('1', '确认收货后退货退款'), ('2', '支付成功未发货退款')], default='1', help_text='退货类型', max_length=1),
        ),
        migrations.AlterField(
            model_name='refund',
            name='shipper',
            field=models.CharField(blank=True, default='', help_text='快递', max_length=255),
        ),
        migrations.AlterField(
            model_name='refund',
            name='shipper_entered',
            field=models.BooleanField(default=False, help_text='上传快递单号时间'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='shipper_sn',
            field=models.CharField(blank=True, default='', help_text='快递单号', max_length=255),
        ),
        migrations.AlterField(
            model_name='refund',
            name='sn',
            field=models.CharField(help_text='退货号', max_length=255),
        ),
        migrations.AlterField(
            model_name='refund',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='订单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_refund', to='transactions.Transaction'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='transaction_product',
            field=models.OneToOneField(blank=True, help_text='订单商品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_product_refund', to='transactions.TransactionProduct'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address',
            field=models.ForeignKey(help_text='地址', on_delete=django.db.models.deletion.CASCADE, related_name='address_transactions', to='profiles.Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='closed_datetime',
            field=models.DateTimeField(blank=True, help_text='关闭时间', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coupon_log',
            field=models.OneToOneField(blank=True, default=None, help_text='优惠卷', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_log_transactions', to='coupons.CouponLog'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deal_type',
            field=models.TextField(choices=[('1', '砍价'), ('2', '团购'), ('3', '秒杀'), ('4', '普通购买'), ('5', '会员付费')], default='4', help_text='购买方式', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expired_datetime',
            field=models.DateTimeField(help_text='过期时间'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='express_type',
            field=models.TextField(choices=[('1', '快递'), ('2', '自提')], default='1', help_text='送货方式', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(help_text='商户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_transactions', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, default='', help_text='备注'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='实际支付金额', max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment',
            field=models.TextField(choices=[('1', '支付宝'), ('2', '微信支付')], default='1', help_text='支付方式', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_datetime',
            field=models.DateTimeField(blank=True, help_text='支付时间', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_sn',
            field=models.CharField(blank=True, default='', help_text='支付流水号', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='promotion',
            field=models.ForeignKey(blank=True, help_text='促销', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_transactions', to='promotions.Promotion'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='received_datetime',
            field=models.DateTimeField(blank=True, help_text='确认收回时间', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='review_datetime',
            field=models.DateTimeField(blank=True, help_text='评价时间', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller_note',
            field=models.TextField(blank=True, default='', help_text='商户备注'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller_packaged_datetime',
            field=models.DateTimeField(blank=True, help_text='商户打包时间', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='session',
            field=models.TextField(blank=True, choices=[('1', '周'), ('2', '月'), ('3', '季'), ('4', '年')], default=None, help_text='会员时长', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sn',
            field=models.CharField(help_text='订单SN', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.TextField(choices=[('1', '创建成功-待支付'), ('2', '支付超时-订单关闭'), ('3', '手动关闭订单'), ('4', '支付完成-待发货'), ('5', '已发货-待收货'), ('6', '已收货-待评价'), ('7', '已评价-交易完成')], default='1', help_text='订单状态', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='总价', max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(help_text='订单用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='nums',
            field=models.IntegerField(default=1, help_text='数量'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='商品售出实时价格', max_digits=8),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='product_spec',
            field=models.ForeignKey(help_text='商品规格', on_delete=django.db.models.deletion.CASCADE, related_name='product_spec_transaction_product', to='products.ProductSpec'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='transaction',
            field=models.ForeignKey(help_text='订单', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_transaction_products', to='transactions.Transaction'),
        ),
    ]
