# Generated by Django 3.0.5 on 2020-05-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200427_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deal_type',
            field=models.TextField(choices=[('1', '砍价'), ('2', '团购'), ('3', '秒杀'), ('4', '普通购买')], default='4', help_text='购买方式', max_length=1),
        ),
    ]
