# Generated by Django 3.0.5 on 2020-05-06 14:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20200506_1453'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='', help_text='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_joined',
            field=models.TextField(blank=True, help_text='全部登录IP', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='最后登录IP', null=True, unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='商户', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_users', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, default='', help_text='手机号', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='昵称', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='weixin_openid',
            field=models.CharField(blank=True, default='', help_text='微信OPENID', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='weixin_userinfo',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='微信用户信息', null=True),
        ),
    ]
