# Generated by Django 3.0.1 on 2019-12-26 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='商品名称', max_length=255)),
                ('desc', models.TextField(blank=True, default='')),
                ('nums', models.IntegerField(default=1)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_stocks', to='merchant.Merchant')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nums', models.IntegerField(default=1)),
                ('name', models.CharField(help_text='时间+进货内容', max_length=255)),
                ('note', models.TextField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_replenish_logs', to='merchant.Merchant')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_replenish_logs', to='inventory.Stock')),
            ],
            options={
                'verbose_name': '进货日志',
                'verbose_name_plural': '进货日志',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
