# Generated by Django 3.0.5 on 2020-05-06 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant', '0003_auto_20200506_1453'),
        ('inventory', '0002_replenishlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replenishlog',
            name='merchant',
            field=models.ForeignKey(help_text='商户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_replenish_logs', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='replenishlog',
            name='nums',
            field=models.IntegerField(default=1, help_text='数量'),
        ),
        migrations.AlterField(
            model_name='replenishlog',
            name='stock',
            field=models.ForeignKey(help_text='库存', on_delete=django.db.models.deletion.CASCADE, related_name='stock_replenish_logs', to='inventory.Stock'),
        ),
        migrations.AlterField(
            model_name='replenishlog',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_replenish_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='desc',
            field=models.TextField(blank=True, default='', help_text='描述'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='merchant',
            field=models.ForeignKey(help_text='商户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_stocks', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nums',
            field=models.IntegerField(default=1, help_text='库存数量'),
        ),
    ]
