# Generated by Django 3.0.5 on 2020-05-06 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_auto_20200427_1633'),
        ('history', '0002_auto_20191226_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browserhistory',
            name='product',
            field=models.ForeignKey(blank=True, help_text='商品', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_browser_history', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='browserhistory',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_browser_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='keyword',
            field=models.CharField(help_text='搜索关键词', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_search_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
