# Generated by Django 3.0.1 on 2019-12-26 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('open_datetime', models.CharField(default='', max_length=255)),
                ('contact', models.CharField(default='', max_length=255)),
                ('remark', models.TextField(blank=True, default='')),
                ('deleted', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_stores', to='merchant.Merchant')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
