# Generated by Django 3.0.5 on 2020-05-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20200506_1453'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(help_text='门店地址', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='contact',
            field=models.CharField(default='', help_text='联系电话', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='merchant',
            field=models.ForeignKey(help_text='商户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_stores', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='门店名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='open_datetime',
            field=models.CharField(default='', help_text='门店营业时间', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='remark',
            field=models.TextField(blank=True, default='', help_text='备注'),
        ),
    ]
