# Generated by Django 3.0.5 on 2020-05-06 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('growth', '0002_auto_20191226_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='from_points',
            field=models.IntegerField(help_text='变更前积分'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='to_points',
            field=models.IntegerField(help_text='变更后积分'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invite',
            name='left',
            field=models.IntegerField(default=10, help_text='剩余邀请次数'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='shortuuid',
            field=models.CharField(help_text='UUID', max_length=255),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.OneToOneField(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_invite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='desc',
            field=models.CharField(default='', help_text='描述', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='invite',
            field=models.ForeignKey(help_text='邀请', on_delete=django.db.models.deletion.CASCADE, related_name='invite_logs', to='growth.Invite'),
        ),
        migrations.AlterField(
            model_name='log',
            name='to_user',
            field=models.ForeignKey(help_text='被邀请用户', on_delete=django.db.models.deletion.CASCADE, related_name='to_user_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
